my_matrix <- matrix((1:12), nrow=3)
print(my_matrix)
print(apply(my_matrix, 1, max))
print(apply(my_matrix, 2, sum))
print(apply(my_matrix, 2, cumsum))
print(apply(my_matrix, 2, range))
mean_squared_vals <- function(x) mean(x**2)
print(apply(my_matrix, 1, mean_squared_vals))
print(apply(my_matrix, 2, mean_squared_vals))
print(apply(my_matrix, c(1,2), mean_squared_vals))